config/routes.rb
DeSimplifyYourVote::Application.routes.draw do
  resources :reasons

  resources :responses

  root :to => 'responses#new'

end

app/models/reason.rb
class Reason < ActiveRecord::Base
  attr_accessible :critique, :response_id, :why
  
  validate do |reason|
    errors.add(:base, "Must include at least one of: critique, reason.") unless !(reason.critique.empty? && reason.why.empty?)
  end
  
  belongs_to :response
end

app/models/response.rb
class Response < ActiveRecord::Base
  attr_accessible :ip_address, :user_agent, :who
  
  validates_presence_of :ip_address, :user_agent, :who
  validates_inclusion_of :who, :in => ['obama', 'romney', 'independent', 'didnt_vote']
  
  has_many :reasons
  accepts_nested_attributes_for :reasons
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/reasons_controller.rb
class ReasonsController < ApplicationController
  # GET /reasons
  # GET /reasons.json
  def index
    @reasons = Reason.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @reasons }
    end
  end

  # GET /reasons/1
  # GET /reasons/1.json
  def show
    @reason = Reason.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @reason }
    end
  end

  # GET /reasons/new
  # GET /reasons/new.json
  def new
    @reason = Reason.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @reason }
    end
  end

  # GET /reasons/1/edit
  def edit
    @reason = Reason.find(params[:id])
  end

  # POST /reasons
  # POST /reasons.json
  def create
    @reason = Reason.new(params[:reason])

    respond_to do |format|
      if @reason.save
        format.html { redirect_to @reason, notice: 'Reason was successfully created.' }
        format.json { render json: @reason, status: :created, location: @reason }
      else
        format.html { render action: "new" }
        format.json { render json: @reason.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /reasons/1
  # PUT /reasons/1.json
  def update
    @reason = Reason.find(params[:id])

    respond_to do |format|
      if @reason.update_attributes(params[:reason])
        format.html { redirect_to @reason, notice: 'Reason was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @reason.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reasons/1
  # DELETE /reasons/1.json
  def destroy
    @reason = Reason.find(params[:id])
    @reason.destroy

    respond_to do |format|
      format.html { redirect_to reasons_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController
  # GET /responses/new
  # GET /responses/new.json
  def new
    @response = Response.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @response }
    end
  end

  # POST /responses
  # POST /responses.json
  def create
    @response = Response.new
    
    reason = Reason.new
    reason.why = params[:response][:reason][:why]
    reason.critique = params[:response][:reason][:critique]
    @response.reasons = [reason]

    @response.who = params[:response][:who]
    @response.ip_address = request.remote_ip
    @response.user_agent = request.env['HTTP_USER_AGENT']

    respond_to do |format|
      if @response.save
        format.html { redirect_to root_url, notice: 'Your response was successfully submitted! Thanks for taking the time to affect change in our government.' }
        format.json { render json: @response, status: :created, location: @response }
      else
        format.html { render action: "new" }
        format.json { render json: @response.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reasons_helper.rb
module ReasonsHelper
end

app/helpers/responses_helper.rb
module ResponsesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>De-Simplify Your Vote</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div id="container">
    <div id="header">
      DSYV
    </div>
    <div id="content">
      <%= yield %>
    </div>
  </div>

</body>
</html>

app/views/reasons/_form.html.erb
<%= form_for(@reason) do |f| %>
  <% if @reason.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reason.errors.count, "error") %> prohibited this reason from being saved:</h2>

      <ul>
      <% @reason.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :why %><br />
    <%= f.text_area :why %>
  </div>
  <div class="field">
    <%= f.label :critique %><br />
    <%= f.text_area :critique %>
  </div>
  <div class="field">
    <%= f.label :response_id %><br />
    <%= f.number_field :response_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reasons/edit.html.erb
<h1>Editing reason</h1>

<%= render 'form' %>

<%= link_to 'Show', @reason %> |
<%= link_to 'Back', reasons_path %>

app/views/reasons/index.html.erb
<h1>Listing reasons</h1>

<table>
  <tr>
    <th>Why</th>
    <th>Critique</th>
    <th>Response</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @reasons.each do |reason| %>
  <tr>
    <td><%= reason.why %></td>
    <td><%= reason.critique %></td>
    <td><%= reason.response_id %></td>
    <td><%= link_to 'Show', reason %></td>
    <td><%= link_to 'Edit', edit_reason_path(reason) %></td>
    <td><%= link_to 'Destroy', reason, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Reason', new_reason_path %>

app/views/reasons/new.html.erb
<h1>New reason</h1>

<%= render 'form' %>

<%= link_to 'Back', reasons_path %>

app/views/reasons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Why:</b>
  <%= @reason.why %>
</p>

<p>
  <b>Critique:</b>
  <%= @reason.critique %>
</p>

<p>
  <b>Response:</b>
  <%= @reason.response_id %>
</p>


<%= link_to 'Edit', edit_reason_path(@reason) %> |
<%= link_to 'Back', reasons_path %>

app/views/responses/_reason_fields.html.erb
<div id="why">
  <h3>I voted for you because...</h3>
  <%= f.text_area :why %>
</div>
<div id="critique">
  <h3>...but I would like to see a change in your position on...</h3>
  <%= f.text_area :critique %>
</div>

app/views/responses/new.html.erb
<%= form_for(@response) do |f| %>
  <h2>Dear <span id="candidate_name">Obama</span>,</h2>
  <% if @response.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@response.errors.count, "error") %> prohibited this response from being saved:</h2>
      <ul>
      <% @response.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.fields_for :reason do |builder| %>
  <%= render 'reason_fields', :f => builder %>
  <% end %>
  <div class="field">
    <%= f.hidden_field :who, :value => "obama" %>
  </div>
  <div class="actions">
    <%= f.submit 'Send in Thoughts' %>
  </div>
<% end %>